### ISSUE TITLE
Bindings for languages + frameworks

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#162]
We want it to be as simple to use Mapzen Search / Pelias as possible. So lets build some bindings to make it easy to use in various languages + projects.

* [ ] Javascript (not just node -- subsumes pelias/pelias#72 and pelias/api#80)
* [ ] Python
 * [ ] [GeoPy framework](https://github.com/geopy/geopy) is a major user of various geocoding clients
* [ ] QGIS [like nominatim](https://plugins.qgis.org/plugins/nominatim/) (thx @nvkelso)

Comment or edit to add more

**Comment by riordan** [comment]
Added [RubyGeocoder](http://www.rubygeocoder.com/) (via @drewda)

**Comment by drewda** [comment]
FYI, I was chatting with @stevevance recently and he mentioned that Mapzen Search would be relevant to a project of his if it were available through that PHP geocoding library.

**Comment by stevevance** [comment]
Yep, and `geocoder-php` is the library I'm using. It has a "chain" method that allows you to have "fallback" geocoders in case the first one isn't good enough. I want to put Mapzen Search first in the chain!

**Comment by dianashk** [comment]
@stevevance, we would be really excited and grateful if you were to add Mapzen Search to `geocoder-php`. Is there anything we can do to help you set that up? We don't have a lot of php know-how on the team, but would do everything we can to help make this happen.

**Comment by stevevance** [comment]
@dianashk I think there's something I could do. I've never looked into how to write a binding. I've started an issue to discuss my progress with you.
