### ISSUE TITLE
Create acceptance tests for 4Shapes -> WoF

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#218]
There are several issues with Quattroshapes data that we believe should be resolved with WoF.

Create Acceptance Tests for these improvements:

- [ ] Places with missing alpha3 areas (pelias/admin-lookup#23)
- [ ] "Northern" - This is a place (pelias/quattroshapes#30)
- [ ] Poorly encoded quattroshapes (pelias/quattroshapes-patch#9)
