### ISSUE TITLE
Remove duplicate dbmapper code in importers

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#234]
Every importer has code that takes a doc and creates an elasticsearch data object with `_type` and `_index`. This has recently been pulled out into pelias-model (see pelias/model#22), so the duplication can be removed.

All importers need to be updated in order to close this issue:
- [x] [openstreetmap](https://github.com/pelias/openstreetmap/blob/master/stream/dbmapper.js#L9) (addressed in https://github.com/pelias/openstreetmap/pull/107)
- [x] [openaddresses](https://github.com/pelias/openaddresses)  (addressed in pelias/openaddresses#42)
- [x] [geonames](https://github.com/pelias/geonames/blob/master/task/import.js#L126) (addressed in pelias/geonames#30)
- [x] <strike>[quattroshapes](https://github.com/pelias/quattroshapes/blob/master/example/runme.js#L151)</strike> not possible, quattroshapes doesn't use pelias-model
- [x] [whosonfirst](https://github.com/pelias/whosonfirst/blob/master/src/elasticsearchPipeline.js#L13) (addressed in pelias/whosonfirst#37)

**Comment by orangejulius** [comment]
All done, hooray!
