### ISSUE TITLE
Installation / Deployment Milestone Details

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#323]
- avoid Chef ( @trescube )
- create an npm module to do the following
  - [ ] download necessary data
  - [ ] install dependency modules
  - [ ] install elasticsearch??
  - [ ] allow for easy config access
  - [ ] allow user to create/drop schema
- update existing Chef scripts to use the new module

**Comment by dianashk** [comment]
This might actually be handled in docker-compose.

**Comment by orangejulius** [comment]
Yeah, the goal of making it easier to install pelias does look to be entirely solved by our https://github.com/pelias/dockerfiles and https://github.com/pelias/kubernetes repos! While there's a lot left to be done in both of those repos, they're already usable and far enough along that tracking smaller tasks is more valuable than this pretty large and vague task. Closing :tada:!
