### ISSUE TITLE
2016/7/28 build acceptance-test issue tracker

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#390]
- [x] **4 Brooklyn tests** - when these tests were written, Brooklyn was a locality in WOF and Geonames. A while back it became a `borough` in WOF, and finally as of https://github.com/pelias/geonames/pull/100 they are `borough`s in GN as well. So the tests should be updated, or removed.
- [x] **mexico city encoding**: the label changed due to https://github.com/pelias/geonames/pull/93, just update the expectations. the test should check the `county` and `region` fields, but not the `label` field
- [x] **15 call st, billerica, MA**. Looks like an OA issue. We can mark these failed, file an OA issue, make a note in the release notes, and continue on
- [x] **search coarse NYC**. The label changed (improved!) so just update the expected value to the current value
- [x] **WOF Springfield:** ~~test should be updated to expect springfield, MO (which is the highest population Springfield)~~. Test should be updated to only query `locality` layer. This test probably broke because of the new population fields we now use after https://github.com/pelias/whosonfirst/pull/116)
- [x] **WOF Comunidad Foral De Navarra 500 error:** should have been fixed with https://github.com/pelias/api/pull/599, figure out why. Answer: API was not deployed to prod_build before acceptance-tests were run. Once deployed the issue was fixed.

**Comment by avulfson17** [comment]
The issue with WOF Springfield isnt that it returns the wrong Springfield, its that Springfield, MO is listed as a localadmin as opposed to a locality like Springfield, MA. Should the same change still be made?

**Comment by trescube** [comment]
Grr locality vs localadmin... they should be treated as equivalent for our purposes.  This will probably go away when the libpostal integration goes out.  Does anyone else find this immediately pressing?

**Comment by avulfson17** [comment]
i can change it to  "layers": "locality,localadmin", if that seems like a decent fix?

**Comment by orangejulius** [comment]
Yeah, for most users they won't care what comes back. The test case file is called "WOF localities", so maybe we could add a `layers=locality` filter?

**Comment by avulfson17** [comment]
that works too.
