### ISSUE TITLE
Elasticsearch 6 Support

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#719]
Hey team! 

The Elasticsearch team moves very fast, and ~~before we can even add support for [ES5](https://github.com/pelias/pelias/issues/461)~~, ES6 has come out and ES7 is even on the horizon!

The current todo for this is:
- [x] First, support ES5 (tracked in https://github.com/pelias/pelias/issues/461)
- [x] Consolidate on one mapping type in our [schema](https://github.com/pelias/schema/). PRs https://github.com/pelias/schema/pull/293 and https://github.com/pelias/model/pull/95 should take care of this. Also see the Elasticsearch docs on [removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/removal-of-types.html). (See [this one too](https://www.elastic.co/blog/removal-of-mapping-types-elasticsearch))
- [x] Switch all `string` fields to `text` or `keyword`. See [Field datatypes](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html) docs (done in https://github.com/pelias/schema/pull/372)
- [x] Remove `"store": "yes"` mapping settings or switch to `"store": true`
- [x] Change `"index": "no"` to `"index": false` in https://github.com/pelias/schema/blob/master/mappings/partial/boundingbox.json#L3 (done in https://github.com/pelias/schema/pull/372)
- [x] Update queries to remove deprecated parameters (for example, the `match` query and `match_phrase` queries are now completely separate). See https://github.com/pelias/query/issues/95 and https://github.com/pelias/api/issues/1261 (done in https://github.com/pelias/api/pull/1354)
- [x] Improve use of synonyms as per https://github.com/pelias/schema/issues/381, resolved in https://github.com/pelias/schema/pull/390
- [x] Update and test https://github.com/pelias/terraform-elasticsearch and https://github.com/pelias/packer-elasticsearch with ES6 (https://github.com/pelias/packer-elasticsearch/pull/1)
- [x] Write and test a new pelias Docker image for ES 6 (https://github.com/pelias/docker/pull/133)
- [x] Determine what else breaks and fix it (GREATLY aided by the work in https://github.com/pelias/schema/issues/316)
- [x] Update `curl` scripts for [strict content-type checking](https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests) (https://github.com/geocodeearth/terraform/pull/76, https://github.com/orangejulius/elasticsearch-bash-utils/pull/1, https://github.com/pelias/terraform-elasticsearch/pull/7)
- [x] Update `curl` scripts to use `pretty=true` instead of `pretty=1`
- [x] It seems as though the autocomplete balance has changed slightly, causing `focus.point` search queries to not work as expected. Setting `"weight": 3` instead of `"weight": 2` for the `function_score` query resolves this. https://github.com/pelias/api/pull/1393
- [x] Update `pelias/docker` elasticsearch image versions https://github.com/pelias/docker/pull/143

Release checklist:
- [x] `docker` https://github.com/pelias/docker/pull/144
- [x] `packer-elasticsearch` https://github.com/pelias/packer-elasticsearch/pull/1
- [x] `config` https://github.com/pelias/config/pull/117

Documentation updates:
**note: we will officially be targeting `6.8.5`, please update any references to older versions (in either the 5 or 6 series)**
- [x] https://github.com/pelias/documentation/blob/master/requirements.md#elasticsearch (https://github.com/pelias/documentation/pull/264)
- [x] https://github.com/pelias/documentation/blob/master/pelias_from_scratch.md#install-elasticsearch (https://github.com/pelias/documentation/pull/264)
- [x] https://github.com/pelias/pelias/#database (https://github.com/pelias/pelias/pull/840)
- [x] https://github.com/pelias/schema/#running-elasticsearch-in-docker-for-testing-purposes (https://github.com/pelias/schema/pull/404)

Remove ES5 support:
**these should be marked as breaking changes**
- [ ] `terraform-elasticsearch` https://github.com/pelias/terraform-elasticsearch/pull/11 (is this backwards compatible!?)
- [ ] `schema` https://github.com/pelias/schema/pull/394

**Comment by thucnc** [comment]
It would be greater if there is a good migration plan from ES 2.4.

**Comment by karussell** [comment]
Not sure if it helps, but photon did also this migration and at the end it went through

https://github.com/komoot/photon/pull/254

(and a few other follow up issues)

The most notable changes: the index got much bigger (we have not yet investigated why) and reverse geocoding got much faster.

**Comment by orangejulius** [comment]
@karussell thanks for the valuable info. Index size getting bigger would be a big deal for Pelias, our global indices are already big enough :)

But faster reverse geocoding would be very welcome.

**Comment by MaherBTA** [comment]
Hi,
I think you did the first step by using one single type field. great job! 
How can I participate ?

**Comment by orangejulius** [comment]
Hey @MaherBTA,
A big help would be a pull request, or even just a branch, with the changes you made for ES6 compared to the pelias/schema repository. With those commits I can rebase things around and start merging stuff.

**Comment by missinglink** [comment]
We have a commercial sponsor for an ES6 upgrade, so it's likely that this will go-ahead soon and we hope to have it merged before the end of the year.

We'd like to hear input from the community about what needs to be changed and if they have time to code or review the new version.

cc/ @Joxit

**Comment by orangejulius** [comment]
We're getting pretty close to working ES6 support in mainline Pelias. I've updated the checklist above, here's roughly what has to be done:

## Finish moving off of multiple Elasticsearch types

We just merged https://github.com/pelias/model/pull/95 which means none of the importers will create documents with types other than `doc`. We probably have to wait about a month or so, then we can merge https://github.com/pelias/model/pull/95 and finish that journey for good!

## Build and test a new ES6 pelias docker image

This is started in https://github.com/pelias/docker/pull/133. The initial work was pretty straightforward, but there will certainly be followup tweaks.

## Update pelias/api queries to use ES6 compatible query format

Most of the work will be in the query views embedded in the API, for example https://github.com/pelias/api/blob/master/query/view/ngrams_strict.js, which uses a variant of the `match_phrase` query which is no longer supported. This will likely be the biggest remaining development task. It also might be blocked by work to merge the new [Pelias parser](https://github.com/pelias/api/pull/1287), since they both touch the query views.

## Upgrade infrastructure code for ES6

For example, https://github.com/pelias/terraform-elasticsearch.

## Start running larger builds and assess performance and result quality

This is the biggest unknown in terms of time, since there is almost always something different in a new ES version that affects reliable operation.

**Comment by orangejulius** [comment]
I've just opened up https://github.com/pelias/schema/issues/381 that describes an issue with the synonym token filter in ES6. Looks like we have a little bit of work to do there before we can support ES6.

**Comment by missinglink** [comment]
Okay, so I'm happy to say that Elasticsearch 6 support is pretty much complete (and ES7 support is also not far off).
It is now possible to generate ES6 builds and I expect that there will be no more changes required to `pelias/schema`.
There is one query bug which is outstanding, I've added a bullet point above and I'll have a look at resolving that next week.

One of the major benefits of ES6 is that the index consumes less than half as much disk as ES5 🎉 
see: https://www.diffchecker.com/hXKddoWS
more info: https://www.elastic.co/blog/minimize-index-storage-size-elasticsearch-6-0

Heads-up we will likely be moving to ES6 as our standard supported version and dropping support for ES2.4 next week.

**Comment by missinglink** [comment]
@pelias/contributors we are hoping to merge this today, feedback welcome!

**Comment by missinglink** [comment]
Today I built a `pelias/docker` project on ES5 then shut it down (keeping the index on disk) and started an ES6 server over the top of the existing ES5 index, confirming that indices built on 5 are compatible with 6 (for now at least).

If anyone in the future is having issues upgrading from ES5 to ES6 I can confirm the following configuration is interoperable between both of those two versions:

```bash
"pelias/elasticsearch:6.8.5"
"sha256:d1016e57030a8a4db5fb32a9b716e84645dc9be6b1a41467fb16ea1cbf2a8f65"

"pelias/interpolation:master"
"sha256:e17a6813035763e574d046caab6757e9bcb9da44d2dc2040c43f7c142c103fc7"

"pelias/libpostal-service:latest"
"sha256:0ca7ded56c25bcc8aa55dcd164b039af2701e7e281a60a69ee4004d6c1e73b22"

"pelias/placeholder:master"
"sha256:980225cabfe2430f686eacab0f9289c1b43168fcc50e68ffa648538a54f2aef0"

"pelias/api:master"
"sha256:fcfcd54a391009130ce322d5cc720c515af178555954febcb1365f86d9ec492a"

"pelias/pip-service:master"
"sha256:5b8eb93a8f60c1932899c7d01095198a7e821268094484e0cfd4cc077ec1cfdc"
```

**Comment by orangejulius** [comment]
All the final PRs for ES6 support look good.

We will also have to update documentation:
- [ ] https://github.com/pelias/documentation/blob/master/requirements.md#elasticsearch
- [ ] https://github.com/pelias/pelias/#database
- [ ] https://github.com/pelias/schema/#running-elasticsearch-in-docker-for-testing-purposes

**Comment by missinglink** [comment]
I've begun merging these PRs, they will be done in a controlled fashion and so it might take some time to complete all the merging.

The `pelias/docker` repo has been upgraded so please test and provide feedback.

**Comment by missinglink** [comment]
Seems X-Pack (which previously required a license) is now free as part of ES6 so those tools will be available now in our elasticsearch images.

If for some reason we prefer to omit these features there is a separate OSS build which excludes them, although they don't seem to publish docker containers of it.

More info: https://www.elastic.co/what-is/open-x-pack

**Comment by missinglink** [comment]
This work is complete and Elasticsearch `6.8.5` release is now the officially supported version 🎉 

**All new builds should target 6.8.5 or later**, we have officially **dropped support for new builds on elasticsearch 5**.
Once you've performed a build on 6 we expect that build to be compatible with both 6 & 7 🚀.

If you're not able to upgrade immediately I would strongly recommend you **pin all your dependencies now** until you're able to do so, we provide immutable docker containers which makes this task quick and easy.

Version `5.6.12` will continue to be supported only as long as it is listed in our [build matrix](https://travis-ci.org/pelias/schema).
We expect to completely drop support for ES5 in January 2020 so please **do a rebuild on ES6 now to avoid breaking changes!**

🙇
